//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Course.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ClientId { get; set; }
		[Required]
		[StringLength(maximumLength:10, ErrorMessage = "{0} 程ぃ禬筁{1}じ")]
		[DisplayName("")]
		public string FirstName { get; set; }
		[Required]
		[StringLength(maximumLength: 5, ErrorMessage = "{0} 程ぃ禬筁{1}じ")]
		[DisplayName("い丁")]
		public string MiddleName { get; set; }
		[Required]
		[StringLength(maximumLength: 10, ErrorMessage = "{0} 程ぃ禬筁{1}じ")]
		[DisplayName("﹎")]
		public string LastName { get; set; }
		[Required]
		[RegularExpression("[MF]", ErrorMessage = "{0}逆块M┪F")]
		[DisplayName("┦")]
		public string Gender { get; set; }
		[DisplayName("ネら")]
		[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
		public Nullable<System.DateTime> DateOfBirth { get; set; }
		[DisplayName("獺ノ单")]
		public Nullable<double> CreditRating { get; set; }
        public string XCode { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public string TelephoneNumber { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Notes { get; set; }
    
        public virtual Occupation Occupation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
